# Generated by Django 2.0.7 on 2018-07-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20180717_1907'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='interview',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.Answer'),
        ),
    ]
