# Generated by Django 2.0.7 on 2018-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20180717_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
